### ISSUE TITLE
[Help]: Button to toggle dark mode

### ISSUE THREAD

**Issue by fockboi-lgtm** [hanwenguo/hugo-theme-nostyleplease#7]
Hello, 

I was wondering if there's any way to add this feature of adding a button to toggle dark mode/light mode. 
I understand that this might not be in the interest of everyone, but I would appreciate any pointers on how to do the same. 

Thanks

**Comment by Masellum** [comment]
Hello, 
Sorry for being late to reply. This feature might not be added since after some consideration I didn't figure out where the best place is to put the toggle button at and how the button should look like. Nevertheless, this feature is not hard to implement. Just add a button to toggle the `a` attribute of `<body>` between empty `light` and `dark`. Wish this would help.
